extcode/cart

Classes/Controller/CartController.php
Classes/Domain/Model/Cart/Cart.php
Classes/Utility/ParserUtility.php

* fix cart->count recalculation after update items amount via cart
* fix misused comparison operator
* use array_key_exists instead of key_exists

cart count was not updated after changing the amount of items in basket view

---

Configuration/TCA/tx_cart_domain_model_coupon.php
Configuration/TCA/tx_cart_domain_model_tag.php

I have updated the language file links to the current state and added a renderType (without this it comes to the error in backend view in 10.4).

[BUGFIX] Language and renderType

---

Classes/Controller/Cart/CartController.php
Classes/Controller/Cart/OrderController.php
Classes/Domain/Model/Cart/Cart.php
Classes/Domain/Model/Cart/Service.php
Classes/EventListener/Order/Create/Number.php
Classes/EventListener/Order/Finish/ClearCart.php
Classes/EventListener/Order/Finish/Email.php
Classes/Hooks/MailAttachmentHook.php

I fixed some PHP 8 warnings in my project. Feel free to merge all or pick some.

Fix some PHP 8 warnings

---

Build/Sources/JavaScript/add_to_cart.js
Resources/Public/JavaScript/add_to_cart.js

The JS for the form finisher tried to have access
to JS methods which were out of scope.

[BUGFIX] JS for form finisher can access functions

---

Classes/Domain/Model/Cart/Cart.php

[BUGFIX] Fix service_attribute_max logic

---

Build/Sources/JavaScript/add_to_cart.js
Build/Sources/JavaScript/change_be_variant.js
Build/Sources/JavaScript/helper/dispatch_custom_event.js
Build/Sources/JavaScript/update_country.js
Build/Sources/JavaScript/update_currency.js
Build/Sources/JavaScript/update_payment_shipping.js
Documentation/Developer/Index.rst
Documentation/Developer/JavaScript-Events/Index.rst
Resources/Public/JavaScript/add_to_cart.js
Resources/Public/JavaScript/change_be_variant.js
Resources/Public/JavaScript/update_country.js
Resources/Public/JavaScript/update_currency.js
Resources/Public/JavaScript/update_payment_shipping.js

Improve the DX with JS custom events and document them.

Improve and document JS custom events

---

Documentation/Administrator/Configuration/Cart/ConsentCheckboxes/Index.rst

Document correct instructions how to hide the
checkboxes of the cart.
Fixes #151

[DOCS] Correct hiding of checkboxes

---

.editorconfig
.github/workflows/ci.yaml
Build/Sources/JavaScript/add_to_cart.js
Build/Sources/JavaScript/change_be_variant.js
Build/Sources/JavaScript/helper/dispatch_custom_event.js
Build/Sources/JavaScript/helper/html_helper.js
Build/Sources/JavaScript/prevent_multi_submit.js
Build/Sources/JavaScript/update_country.js
Build/Sources/JavaScript/update_currency.js
Build/Sources/JavaScript/update_payment_shipping.js
Build/Sources/eslint.config.mjs
Build/Sources/package.json
Resources/Public/JavaScript/add_to_cart.js
Resources/Public/JavaScript/change_be_variant.js
Resources/Public/JavaScript/prevent_multi_submit.js
Resources/Public/JavaScript/update_country.js
Resources/Public/JavaScript/update_currency.js
Resources/Public/JavaScript/update_payment_shipping.js

Add linting for Javascript and add it to CI.
Fixes #448

[TASK] Add JavaScript linting

---

Classes/Controller/Order/OrderController.php

Switch usage of $GLOBALS['TSFE'] to Context API
to retrieve FE user UID.

[TASK] Use Context API instead of global TSFE

---

Resources/Private/Partials/Cart/ProductForm/ProductList.html

Add missing "v" for argument key "value".

[BUGFIX] Use correct argument in textfield

---

Tests/Functional/Utility/ParserUtilityTest.php

[BUGFIX] Add countries to test configuration

---

Classes/Controller/Backend/Order/DocumentController.php

[BUGFIX] Fix broken document download

---

.github/workflows/ci.yaml

[TASK] Add PHPUnit to github actions

---

Configuration/Backend/Modules.php

[BUGFIX] Fix module access

---

Classes/Controller/Cart/CartController.php

Due to the implementation of the PRG pattern the
errors directly next to the errorneous fields were no longer displayed.
With this commit the PRG pattern will only be
used if no errors occur during the current step.
Fixes: #532

[BUGFIX] Show error messages in multistep checkout

---

Classes/Domain/Model/Cart/Product.php

Fix for this issue https://github.com/extcode/cart/issues/559

[BUGFIX] Accept best price to be 0

---

Classes/Domain/Model/Cart/Service.php

[BUGFIX] Avoid undefined array key error

---

Classes/Service/AbstractConfigurationFromTypoScriptService.php

[BUGFIX] Check for existing array key

---

Classes/ViewHelpers/AdditionalJsonViewHelper.php

[BUGFIX] Fill up array for explode if only one item will be returned

---

Documentation/Developer/Events/Index.rst

PaymentEvent and StockEvent were documented
in wrong order.

[DOCS] Show actual sequence of Events during order

---

Classes/EventListener/Order/Create/Order.php
Classes/EventListener/Order/Finish/ClearCart.php
Classes/EventListener/Order/Finish/Email.php

[TASK] Use EventInterface in EventListener

---

.gitlab-ci.yml

[TASK] Remove SonarCube from GitLab CI

---

Build/Sources/JavaScript/add_to_cart.js
Documentation/Changelog/10.0/Breaking-614-AllowMoreThanOneCartPreviewInPage
Documentation/Changelog/10.0/Feature-614-AllowMoreThanOneCartPreviewInPage
Documentation/Changelog/10.0/Index.rst
Resources/Private/Templates/Cart/CartPreview/Show.html
Resources/Public/JavaScript/add_to_cart.js

[TASK] Allow more than one CartPreview in page

---

Configuration/Backend/Modules.php

[BUGFIX] Change label configuration for cart main module

---

Classes/Domain/Model/Cart/AdditionalDataTrait.php

[BUGFIX] Initialize $additionals property with empty array
